[manager]
linemode = "size"
show_symlink = true
ratio = [2,4,3]

[preview]
max_width  = 1500
max_height = 1500

[opener]
play = [
	{run = 'smplayer "$@" &> /dev/null', block = true, for = "linux"},
]
edit = [
	{run = 'nvim "$@"', block = true, for = "linux"},
]

[open]
rules = [
	{mime = "video/*", use = "play"},
	{mime = "audio/*", use = "play"},
	{mime = "text/*",  use = "edit"},
]
